# Generated by Django 3.1.7 on 2021-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='max_pax',
        ),
        migrations.AddField(
            model_name='club',
            name='holiday_max_pax',
            field=models.IntegerField(default=4, verbose_name='holiday maximum PAX'),
        ),
        migrations.AddField(
            model_name='club',
            name='holiday_min_pax',
            field=models.IntegerField(default=1, verbose_name='holiday minimum PAX'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekday_max_pax',
            field=models.IntegerField(default=4, verbose_name='Weekday minimum PAX'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekday_min_pax',
            field=models.IntegerField(default=1, verbose_name='Weekday minimum PAX'),
        ),
    ]
