# Generated by Django 3.1.7 on 2021-03-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20210314_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='weekday_max_pax',
            field=models.IntegerField(default=4, verbose_name='Weekday maximum PAX'),
        ),
    ]
