# Generated by Django 3.1.7 on 2021-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20210314_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='distance_from_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance from airport'),
        ),
        migrations.AddField(
            model_name='club',
            name='distance_from_downtown',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance from downtown'),
        ),
    ]
