# Generated by Django 3.1.7 on 2021-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20210314_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='estimated_time_from_airport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated time from airport'),
        ),
        migrations.AddField(
            model_name='club',
            name='estimated_time_from_downtown',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated time from downtown'),
        ),
    ]
