# Generated by Django 3.1.7 on 2021-03-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_auto_20210314_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='par',
            field=models.IntegerField(blank=True, default=72, null=True, verbose_name='Par'),
        ),
        migrations.AddField(
            model_name='club',
            name='yardage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total yardage'),
        ),
    ]
