# Generated by Django 3.1.7 on 2021-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0008_auto_20210314_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='designer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course designer'),
        ),
    ]
